# Generated by Django 5.0.2 on 2024-02-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='House number')),
                ('level', models.IntegerField(blank=True, choices=[(0, 'Factory'), (1, 'Retailer'), (2, 'Individual Entrepreneur')], null=True, verbose_name='Level')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Is supplier')),
            ],
            options={
                'verbose_name': 'Network node',
                'verbose_name_plural': 'Network nodes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('market_date', models.DateField(blank=True, null=True, verbose_name='Market date')),
                ('debt_to_supplier', models.FloatField(blank=True, null=True, verbose_name='Debt to supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading_platform.networknode', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='networknode',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='trading_platform.product', verbose_name='Products'),
        ),
    ]
