# Generated by Django 5.0.2 on 2024-02-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='products',
            field=models.ManyToManyField(to='trading_platform.product', verbose_name='Products'),
        ),
    ]
